vim.cmd("set expandtab")
vim.cmd("set tabstop=4")
vim.cmd("set softtabstop=4")
vim.cmd("set shiftwidth=4")
vim.cmd("set encoding=utf-8")
vim.cmd("set nocompatible")
vim.cmd("set showmatch")
vim.cmd("set ignorecase")
vim.cmd("set mouse=v")
vim.cmd("set hlsearch")
vim.cmd("set incsearch")
vim.cmd("set tabstop=4")
vim.cmd("set softtabstop=4")
vim.cmd("set shiftwidth=4")
vim.cmd("set autoindent")
vim.cmd("set number")
vim.cmd("set wildmode=longest,list")
-- set cc=80
vim.cmd("filetype plugin indent on")
vim.cmd("syntax on")
vim.cmd("set mouse=a")
vim.cmd("set clipboard=unnamedplus")
vim.cmd("filetype plugin on")
vim.cmd("set cursorline")
vim.cmd("set ttyfast")
vim.cmd("set noswapfile")
vim.cmd("set termguicolors")
vim.g.mapleader = " "
-- Key Remaps
vim.keymap.set('n', '<C-n>', ':tabnext<CR>')
vim.keymap.set('n'. 'p', 'pgvy', { noremap = true, silent = true}) -- "p" now is mapped to "pgvy" so it yanks latest pasted line 
